### ISSUE TITLE
Add support for .NET 5

### ISSUE THREAD

**Issue by gayankanishka** [jcansdale/gpr#101]
I am getting the below error when I try to push with `gpr` in a GitHub action. 
Github action is using `dotnet-version: 5.0.100-rc.2.20479.15` for build process.

![image](https://user-images.githubusercontent.com/32380979/98147779-c0c53280-1ef2-11eb-9c40-dbe8d3af7cfe.png)

Please do let me know if further details are needed. Thanks in advance.

**Comment by andlewis** [comment]
Any chance we can get this merged in as soon as possible?

**Comment by jcansdale** [comment]
@gayankanishka @andlewis,

I've just merged https://github.com/jcansdale/gpr/pull/99, which should allot the tool to run when only .NET 5.0 is installed.

Sorry about the long delay. 😊 

Is this issue okay to close?

**Comment by jcansdale** [comment]
I think this is addressed by #99. 🤞🏻
