### ISSUE TITLE
Feature: Set default repository and automatically add repository url and type on push

### ISSUE THREAD

**Issue by Swoorup** [jcansdale/gpr#48]
I work with packages having different style of nuspecs. paket.template, nuspec and the proj XML ones. 

Use case is, often sometimes I add a feature to someone else open sourced library, and want to bundle it straightaway instead of waiting for them to merge the pull request and use it. I wouldn't want to modify the nuspec field repository url and type on the library but still upload them to my own github package registry. 

It would be handy to have a way to do a push where this library would automatically add or change the repository url and type and push it into a centralized github repository.

**Comment by jcansdale** [comment]
This should be possible using:
https://docs.microsoft.com/en-us/dotnet/api/system.io.compression.zipfile?view=netframework-4.8

I'll look into doing this! 😄

**Comment by Swoorup** [comment]
Might as well add a version override or a prefix too to force alternative package selection :+1:

**Comment by jcansdale** [comment]
> Might as well add a version override or a prefix too to force alternative package selection 👍

I like it, thanks for the suggestion!

This is exactly what I did [here](https://github.com/jcansdale/octokit.graphql.net/packages/119973?version=0.1.4-preview-package-deletes) when I needed support for the preview package deletion API in Octokit.GraphQL.

**Comment by jcansdale** [comment]
For reference, here are the `repository` and `version` elements in a `*.nuspec` file:

```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
  <metadata>
    <version>0.1.121-gdd48c0cae9</version>
    <repository url="https://github.com/jcansdale/gpr" />
  </metadata>
</package>
```

The idea would be to allow the overriding of these as part of the publish. For example:

```
gpr push your.nupkg --repository-url https://github.com/jcansdale/gpr --version 0.1.121-custom-label
```

More suggestions how this might work are welcome. 😄

**Comment by peters** [comment]
@Swoorup PR #53
