### ISSUE TITLE
`gpr push` should attempt to publish all packages

### ISSUE THREAD

**Issue by jcansdale** [jcansdale/gpr#67]
At the moment it fails after attempting to push package versions that already exist:
https://github.com/jcansdale-test/packages/runs/785460975?check_suite_focus=true#step:7:13

@peters I'm wondering if we should differentiate between expected errors where `X-Nuget-Warning` is set and unexpected ones?

I think we should be treating these as warnings. 🙂 

```cs
var nugetWarning = response.Headers.FirstOrDefault(h =>
   h.Name.Equals("X-Nuget-Warning", StringComparison.OrdinalIgnoreCase));
```

**Comment by peters** [comment]
@peters IMHO one should always error out on warnings (especially when in a CI scenario) but you should be able to opt-in (bypass) warnings as needed. The difference between the two is that the user has deliberately chosen to ignore the warnings :)

**Comment by jcansdale** [comment]
@peters,

> The difference between the two is that the user has deliberately chosen to ignore said warnings :) In the scenario you describe this can be solved by adding --ignore-duplicates and --ignore-warnings options :)

Well put, you have me convinced! 😄 

I don't completely understand how the `Polly.Policy` works yet. If you had the inclination, I'd love to see a PR for this. Otherwise I'll dig into it when the family are asleep. 😉
