### ISSUE TITLE
Error when path contains a space

### ISSUE THREAD

**Issue by jcansdale** [jcansdale/gpr#70]
I think we might need to get rid of this:
https://github.com/jcansdale/gpr/blob/31072d51beeead1359447deabcaedde3686b863f/src/GprTool/IoExtensions.cs#L25-L37

...and make this a `string[]`:
https://github.com/jcansdale/gpr/blob/31072d51beeead1359447deabcaedde3686b863f/src/GprTool/Program.cs#L555

### How to test

```
gpr push 'C:\Users\Jamie Cansdale\.nuget\packages\**\*' ...
```

**Comment by peters** [comment]
@jcansdale I think you have discovered a bug. This check is meant to check if `GlobPattern` contains multiple filenames. Example: test1.nupkg test2.nupkg. A possible fix is to modify `.Where(x => !Directory.Exists(x)))` to `.Where(x => !Directory.Exists(x) && File.Exists(x)))` and only set `globPattern` to `string.Empty` if `fileNames.Count > 0`

**Comment by jcansdale** [comment]
@peters now that #72 is working, am I correct in thinking we can get rid of the following?

https://github.com/jcansdale/gpr/blob/31072d51beeead1359447deabcaedde3686b863f/src/GprTool/IoExtensions.cs#L25-L37

After #72 is merged, this will work:

```
git push foo.nupkg bar.nupkg
```

I think the following:

```
git push "foo.nupkg bar.nupkg"
```

... should be interpreted as pushing a file called `foo.nupkg bar` with the extension `.nupkg`.

What do you think?
