### ISSUE TITLE
Specifying the version when pushing doesn't work for stripping build metadata

### ISSUE THREAD

**Issue by PathogenDavid** [jcansdale/gpr#92]
As per our discussion here: https://github.community/t/bug-nuget-support-build-metadata-properly/117606/15

It seems `gpr push "*.nupkg" --version 1.0.0` doesn't work if the package's version is `1.0.0+BuildMetadata` because the two versions are considered to be equivalent.

**Comment by jcansdale** [comment]
@PathogenDavid I believe the metadata is now being stipped at the GitHub Packages end, so this shouldn't be an issue.

I'm going to close this issue. Please let me know if I've done this to soon. 😉

**Comment by PathogenDavid** [comment]
I just re-ran my test from August and indeed [everything works as expected](https://github.com/PathogenPlayground/GitHubPackagesBuildMetadataTest/actions/runs/719519778). Thanks a lot for the update and for getting this fixed! 💜
